import logging
try:
    import bot.py
except Exception as e:
    logging.log(e,traceback.logging.log_exc())